name: 'Publish'
on:
  create:
    branches:
      - 'master'

jobs:
  publish:
    if: startsWith(github.repository, 'ModdingX/') && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Build'
        run: |
          ./gradlew \
          -Pversion=${{ github.ref_name }} \
          -PmoddingxUsername=${{ secrets.PUBLISH_USER }} \
          -PmoddingxPassword=${{ secrets.PUBLISH_PASSWORD }} \
          build javadoc publish
      - name: 'Generate .nojekyll marker'
        run: touch build/docs/javadoc/.nojekyll
      - name: 'Publish Javadoc'
        uses: 'JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a'
        with:
          branch: gh-pages
          folder: 'build/docs/javadoc'
          clean: true
          git-config-name: 'Github Actions'
          git-config-email: '<>'
